from __future__ import annotations

from typing import Dict, Set


STANDARD_ACTIONS: Set[str] = {
    "navigate",
    "get_page_text",
    "get_current_url",
    "get_page_html",
    "list_tabs",
    "list_candidates",
    "open_tab",
    "activate_tab",
    "close_tab",
    "resize",
    "click",
    "click_target",
    "type_text",
    "type_target",
    "type_target_and_verify",
    "press_key",
    "run_script",
    "run_script_batch",
    "watch_page_state",
    "watch_target_state",
    "wait_for",
    "wait_for_text",
    "wait_for_text_gone",
    "wait_for_text_change",
    "wait_for_page_stable",
    "wait_for_timeout",
    "inspect_elements",
    "get_active_element",
    "get_interaction_context",
    "describe_target",
    "diagnose_target",
    "diagnose_page",
    "verify_target_visible",
    "verify_target_value",
    "verify_active_element",
    "hover",
    "highlight_target",
    "clear_highlights",
    "mouse_move_xy",
    "mouse_click_xy",
    "mouse_drag_xy",
    "mouse_gesture_path",
    "select_option",
    "handle_dialog",
    "file_upload",
    "navigate_back",
    "navigate_forward",
    "drag_target",
    "get_console_messages",
    "get_page_errors",
    "get_network_requests",
    "clear_debug_buffers",
    "screenshot",
    "get_summary",
    "get_capabilities",
    "snapshot",
    "get_action_trace",
    "verify_text",
    "verify_dialog",
    "verify_element",
}


DEFAULT_NATIVE_ACTIONS: Dict[str, Set[str]] = {
    "official_playwright_mcp": {
        "get_page_text",
        "get_current_url",
        "get_page_html",
        "get_interaction_context",
        "inspect_elements",
        "list_candidates",
        "snapshot",
    },
    "patchright": {
        "get_page_text",
        "get_current_url",
        "get_page_html",
        "get_interaction_context",
        "inspect_elements",
        "list_candidates",
        "snapshot",
    },
    "selenium_uc": {
        "get_page_text",
        "get_current_url",
        "get_page_html",
        "get_interaction_context",
        "inspect_elements",
        "list_candidates",
        "snapshot",
    },
    "playwright_cli": {
        "get_page_text",
        "get_current_url",
        "get_page_html",
        "get_interaction_context",
        "snapshot",
    },
}
